database:
  initConnectionString: "Server=localhost;User Id=sa;Password=rootRoot123;Pooling=true;Min Pool Size=4; Max Pool Size = 4;TrustServerCertificate=True"
  connectionString: "Server=localhost;Database=TestLogApp;User Id=sa;Password=rootRoot123;Pooling=true;Min Pool Size=1; Max Pool Size = 4;TrustServerCertificate=True"