database:
  initConnectionString: "Server=localhost;Database=master;User Id=sa;Password=rootRoot123;TrustServerCertificate=True"
  connectionString: "Server=localhost;Database=TestLogApp;User Id=sa;Password=rootRoot123;;TrustServerCertificate=True"