IF EXISTS (SELECT name FROM sys.databases WHERE name = 'InitTestLogAppSem')
BEGIN
    ALTER DATABASE InitTestLogAppSem SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE InitTestLogAppSem;
END
