database:
  devMode: true #devMode가 true면 실행 시점에 DB를 초기화하고 데이터를 새로 저장합니다. 
  masterConnectionString: "Server=localhost;Database=master;User Id=sa;Password=rootRoot123;TrustServerCertificate=True"
  connectionString: "Server=localhost;Database=LogApp;User Id=sa;Password=rootRoot123;Pooling=true;Min Pool Size=4; Max Pool Size = 4;TrustServerCertificate=True"

csvSource:
  basePath: "resources/csvs"
  fileNames: [ "hospital1", "hospital2", "DS/drugstore1", "DS/drugstore2", "details1" ]