database:
  initConnectionString: "Server=localhost; User Id=sa;Password=rootRoot123; TrustServerCertificate=True"
  connectionString: "Server=localhost;Database=LogApp;User Id=sa;Password=rootRoot123;Pooling=true;Min Pool Size=4; Max Pool Size = 4;TrustServerCertificate=True"