IF
NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Hospital')
BEGIN
CREATE TABLE Hospital
(
    Id       INT PRIMARY KEY IDENTITY(1,1),
    Code     NVARCHAR(100),
    Name     NVARCHAR(100) NOT NULL,
    Address  NVARCHAR(200),
    Location GEOGRAPHY
);

CREATE
SPATIAL INDEX IX_Location ON Hospital(Location);
END

IF
NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DrugStore')
BEGIN
CREATE TABLE DrugStore
(
    Id       INT PRIMARY KEY IDENTITY(1,1),
    Name     NVARCHAR(100) NOT NULL,
    Code     NVARCHAR(100),
    Address  NVARCHAR(200),
    Location GEOGRAPHY
);

CREATE
SPATIAL INDEX Ix_Location ON DrugStore(Location);
END
